### ISSUE TITLE
Removed apps come back

### ISSUE THREAD

**Issue by rasppliances** [Open-Smartwatch/open-smartwatch-os#109]
I commented out the snake and water level apps in main.cpp and uploaded it to my watch.  The first time through the apps. those two apps are missing.  It goes watch face, stop watch, time config, gui congif and back to watch face.  But if I keep going after I get back to watch face, I get snake, stop watch and water level in that order.

[Here's a video that demonstrates what I'm seeing](https://youtu.be/RFBsXpXHAIU).

**Comment by uvwxy** [comment]
That was a copy and paste issue on the develop branch back then. this should be fixed. reopen if this is still the case. thanks :)
