### ISSUE TITLE
Central OTA Service

### ISSUE THREAD

**Issue by Apfelwurm** [Open-Smartwatch/open-smartwatch-os#11]
It would be great if it could be managed to build the firmware centrally (maybe with different app combinations) and ship OTA updates via a central service. The osw than could access it directly via wlan without the need of accessing the ofw from a browser or a smartphone. This feature should include firmware signatures or/and https support

**Comment by uvwxy** [comment]
I think this ticket is ahead of its time, and not required at the moment.
