### ISSUE TITLE
BLE Media Control is resetting the watch

### ISSUE THREAD

**Issue by hugo4715** [Open-Smartwatch/open-smartwatch-os#114]
The BLE Media control app seems to be resetting the watch when switching to another app.

**Comment by uvwxy** [comment]
Is there a stack trace in the serial output?

**Comment by Simonmicro** [comment]
Isn't this a known issue, as the `BLEKeyboard` instance literally does not implement any destructor? Therefore we have a huge memory leak and reactivating the in-memory rendering causes us to run out of it.

**Comment by uvwxy** [comment]
Indeed. BLE Media Control will not usufully work on the light edition. I have designed a new PCB with an additional 4MB ram which will make this usecase more doable.
