### ISSUE TITLE
Rise to wake not working

### ISSUE THREAD

**Issue by RickSeiden** [Open-Smartwatch/open-smartwatch-os#116]
I have configured the rise to wake threshold as low as 0 and as high as 255, and the watch does not wake when I bring up my arm and twist my wrist.

**Comment by uvwxy** [comment]
I had the same issue. thanks for creating a ticket to keep an eye on this.

**Comment by mpegg4** [comment]
Looks like https://github.com/Open-Smartwatch/open-smartwatch-os/issues/119 was related, fixed & closed.  Maybe this ticket is too?

**Comment by AvdHdn** [comment]
I noticed that "tap to wake" does not work on my watch when I manually put it to deep sleep mode.
When the watch would time out by itself (on the clock watchface) the tap to wake function does work.
Do you have the same issue?

**Comment by uvwxy** [comment]
> I noticed that "tap to wake" does not work on my watch when I manually put it to deep sleep mode.
> When the watch would time out by itself (on the clock watchface) the tap to wake function does work.
> Do you have the same issue?

This is intentional: https://github.com/Open-Smartwatch/open-smartwatch-os/blob/master/src/apps/main/switcher.cpp#L44
