### ISSUE TITLE
Digital clock face - text background incorrect after updating color settings using Configuration UI

### ISSUE THREAD

**Issue by mpegg4** [Open-Smartwatch/open-smartwatch-os#120]
Thanks to brrMoment for surfacing this and the collab to identify the fix. 
When updating foreground/background color using Configuration UI, digital watchface (and some other apps) draw text without deriving ui background/foreground color and applying. This creates issue for first time users who are not familiar with coding.

Example digital watchface screenshot with background color issue:
![image](https://user-images.githubusercontent.com/12973737/124027053-44aebc00-d9a7-11eb-9706-421378022d5d.png)

Other switcher apps have this adjustment made:

`hal->gfx()->setTextColor(ui->getPrimaryColor(), ui->getBackgroundColor());`

Suggested fix - update watchface_digital.cpp and add the same color setup before writing text ( maybe in `void OswAppWatchfaceDigital::loop`):

`hal->gfx()->setTextColor(ui->getPrimaryColor(), ui->getBackgroundColor());`

Test of digital clock after applying:

![image](https://user-images.githubusercontent.com/12973737/124030395-00bdb600-d9ab-11eb-9634-c6a34367f575.png)

**Comment by Simonmicro** [comment]
Should be fixed - could you confirm this with a fresh build from the `develop` branch?

**Comment by mpegg4** [comment]
@Simonmicro thanks - will check it out and feedback here and in discord. Awesome work!

**Comment by mpegg4** [comment]
@Simonmicro Ack - looks great now!
