### ISSUE TITLE
An accent color

### ISSUE THREAD

**Issue by Kokofruits1** [Open-Smartwatch/open-smartwatch-os#130]
Could be cool to implement in apps to have a cohesive thing to all of the apps.

**Comment by Simonmicro** [comment]
> cohesive thing

You mean theme?

And we already have this - at least with primary, background, info, warn, error & more colors - please specify what you mean with this.

**Comment by Kokofruits1** [comment]
Oh, cool, didn't know that! I mean it's like a colour that can be accessed by every app and used, for example, a line to give it the same colour. Seems like it's the same as it's already implemented.
