### ISSUE TITLE
WIFI services broken on develop branch

### ISSUE THREAD

**Issue by max9901** [Open-Smartwatch/open-smartwatch-os#138]
I get always get a AP mode with ip adress 0.0.0.0 on the current dev branch.

the master branch works flawlessly.

**Comment by uvwxy** [comment]
Correct, borked on my device too, on it with @Simonmicro

**Comment by Simonmicro** [comment]
@uvwxy Had added some code to get the ULP working - for this an other fork of the Expressif libs was used -> this caused the WiFi to get broken. It is fixed now.
