### ISSUE TITLE
Platform IO Build Error

### ISSUE THREAD

**Issue by krishpranav** [Open-Smartwatch/open-smartwatch-os#143]
Hi @Open-Smartwatch team so I am facing this error when I run this command:
```
pio run -e pico32_LIGHT_EDITION -t upload
```

I am on macOS Big Sur I have installed the requirements that you gave
```
swig, platformio
```

**Comment by krishpranav** [comment]
```
src/apps/_experiments/runtime_test.cpp: In member function 'virtual void OswAppRuntimeTest::setup(OswHal*)':
src/apps/_experiments/runtime_test.cpp:14:31: error: 'MINI_IOT_DEVICENAME' was not declared in this scope
   miniIot = new MiniIotClient(MINI_IOT_DEVICENAME, MINI_IOT_SERVER, wifiSsid.c_str(), wifiPass.c_str());
                               ^
src/apps/_experiments/runtime_test.cpp:14:52: error: 'MINI_IOT_SERVER' was not declared in this scope
   miniIot = new MiniIotClient(MINI_IOT_DEVICENAME, MINI_IOT_SERVER, wifiSsid.c_str(), wifiPass.c_str());
                                                    ^
*** [.pio/build/pico32_GPS_EDITION/src/apps/_experiments/runtime_test.cpp.o] Error 1
========================== [FAILED] Took 9.47 seconds ==========================

Environment         Status    Duration
------------------  --------  ------------
pico32_GPS_EDITION  FAILED    00:00:09.470
==================== 1 failed, 0 succeeded in 00:00:09.470 ====================
```

**Comment by matti04** [comment]
Hello! 
Have you removed the `.example` extension from the `configuration.h` file?

**Comment by krishpranav** [comment]
oh should I do it?

**Comment by krishpranav** [comment]
@matti04 I've just forgetter it i will try it

**Comment by krishpranav** [comment]
compilation terminated.
*** [.pio/build/pico32_LIGHT_EDITION/lib925/Adafruit BME280 Library/Adafruit_BME280.cpp.o] Error 1
Compiling .pio/build/pico32_LIGHT_EDITION/libe10/BME280/BME280.cpp.o
.pio/libdeps/pico32_LIGHT_EDITION/BME280/src/BME280.cpp: In member function 'bool BME280::InitializeFilter()':
.pio/libdeps/pico32_LIGHT_EDITION/BME280/src/BME280.cpp:85:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
.pio/libdeps/pico32_LIGHT_EDITION/BME280/src/BME280.cpp: In member function 'bool BME280::WriteSettings()':
.pio/libdeps/pico32_LIGHT_EDITION/BME280/src/BME280.cpp:122:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
========================= [FAILED] Took 28.33 seconds =========================

Environment           Status    Duration
--------------------  --------  ------------
pico32_LIGHT_EDITION  FAILED    00:00:28.335
==================== 1 failed, 0 succeeded in 00:00:28.335 ====================

**Comment by krishpranav** [comment]
In file included from .pio/libdeps/pico32_LIGHT_EDITION/Adafruit BME280 Library/Adafruit_BME280.cpp:31:0:
.pio/libdeps/pico32_LIGHT_EDITION/Adafruit BME280 Library/Adafruit_BME280.h:26:32: fatal error: Adafruit_I2CDevice.h: No such file or directory

**Comment by krishpranav** [comment]
facing another error

**Comment by uvwxy** [comment]
@krishpranav  please try:

`git checkout develop`
`git submodule update`

then build again.

**Comment by krishpranav** [comment]
> @krishpranav please try:
> 
> `git checkout develop`
> `git submodule update`
> 
> then build again.

ok let me try

**Comment by krishpranav** [comment]
Error: Please specify `upload_port` for environment or use global `--upload-port` option.
For some development platforms it can be a USB flash drive (i.e. /media/<user>/<device name>)
*** [upload] Explicit exit, status 1
================================= [FAILED] Took 115.49 seconds =================================

Environment           Status    Duration
--------------------  --------  ------------
pico32_LIGHT_EDITION  FAILED    00:01:55.487
============================ 1 failed, 0 succeeded in 00:01:55.487 ============================

**Comment by krishpranav** [comment]
it is now showing this error

**Comment by krishpranav** [comment]
any one know to fix it?

**Comment by krishpranav** [comment]
I just run this command:
pio run -e pico32_LIGHT_EDITION -t upload --upload-port 8080

**Comment by krishpranav** [comment]
File "/usr/local/Cellar/platformio/5.1.1/libexec/lib/python3.9/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port 4444: [Errno 2] No such file or directory: '4444'

**Comment by krishpranav** [comment]
I am facing this issue

**Comment by krishpranav** [comment]
x.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port 8080: [Errno 2] No such file or directory: '8080'

**Comment by richtepa** [comment]
> I just run this command:
pio run -e pico32_LIGHT_EDITION -t upload --upload-port 8080

Where does port 8080 come from? Is your watch is plugged in via usb?
On my mac the port is `/dev/cu.serial-*`.
Try checking the ports using `ls /dev/cu.*` in the terminal.

**Comment by krishpranav** [comment]
> > I just run this command:
> > pio run -e pico32_LIGHT_EDITION -t upload --upload-port 8080
> 
> Where does port 8080 come from? Is your watch is plugged in via usb?
> On my mac the port is `/dev/cu.serial-*`.
> Try checking the ports using `ls /dev/cu.*` in the terminal.

ok thanks @richtepa

**Comment by krishpranav** [comment]
I just got confused

**Comment by krishpranav** [comment]
thanks for your help guys
