### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by atellier2** [Open-Smartwatch/open-smartwatch-os#147]
I have a trouble with the brightness.

1. I start the watch 
2. I wait for a deep sleep 
3. I wake-up the watch and try to increase the brightness
=> The brightness is decreased 😯

The problem seems to come from the initialization of the _brightness variable. The variable is initialized to 0 but in the config file it's for example 75.

Do you have the same problem ?

I write this small fix : https://github.com/atellier2/open-smartwatch-os/commit/258ad797f2283878ae875447dc33a2375a2b5fbb

**Comment by simonmicro** [comment]
Cherry-Picked into `develop` - thank you for catching (and fixing) that!
