### ISSUE TITLE
Calendar app

### ISSUE THREAD

**Issue by Kokofruits1** [Open-Smartwatch/open-smartwatch-os#152]
![Open_smart_watch_calendar_fluent design](https://user-images.githubusercontent.com/79061573/130363919-dd04cbe5-abf3-4e19-a101-940a491014da.jpg)

I think that a calendar app could be a great addition to the smart watch. It would use the apps sync functionality (I know it is not made yet) to get this data and then it would display them. The watch itself would only show the events name, description and location.

It would show 2 events on one page, this weeks events only,  and you would scroll through events by pressing buttons up or down. When you hold the top/bottom button it would open a  page for one of the events and show it's full name, full description and location.

It has a similar design language as the #20 latest design by me, so it would have some similarities in it's design to this app.

**Comment by simonmicro** [comment]
Holy sh*t! I love your design language! I've just seen this issue / idea now and i'm very impressed. I think we should invest further into making a proper UI library - but for now: Your design draft is beautiful!

**Comment by Kokofruits1** [comment]
Thank you for liking my design!
For the UI library from a design perspective, I'm not a programmer, just know the basics, I would like to see standardized button label designs (compact and near the buttons), in-built icons, how selected items, loading bars and a way to input a number look.
I would like to work on a design for an alarm clock, weather app, timer and other useful utilities, if you want to work on any of these apps, I would love to help you with the design!
Also, what's happening with the android app? I heard it was being worked on, but I haven't seen anything about it in months.

**Comment by simonmicro** [comment]
>  Also, what's happening with the android app? I heard it was being worked on, but I haven't seen anything about it in months.

Good question... I have no idea!

> For the UI library from a design perspective, I'm not a programmer, just know the basics, I would like to see standardized button label designs (compact and near the buttons), in-built icons, how selected items, loading bars and a way to input a number look.

Next session I plan to rework the current UI class to manage the rendering pipeline and also to allow "fullscreen progress-bars" (useful also in other areas). I think I'll add stuff like drawing some elements for that to it - but we'll see...

**Comment by RuffaloLavoisier** [comment]
@Kokofruits1 
Hi, I'd like to carry out your idea. I would appreciate it if you could let me know the details.

**Comment by Kokofruits1** [comment]
> @Kokofruits1 Hi, I'd like to carry out your idea. I would appreciate it if you could let me know the details.

The app would download the data from the opensmartwach app, then using the calendar permission it would download about a week worth of events to the watch. If the app is never created it could use calDAV, but I have no idea how much space it would require.

Short pressing a button would move a page up or down and long pressing a button will bring the full view for the event. When in the full view you would use the buttons to scroll or to go back. Back button could be the third button, the one on the left side, not as it is in the original design.

**Comment by RuffaloLavoisier** [comment]
@Kokofruits1 

1.Does scrolling only go to the next (future) schedule ?  

2.One schedule in detail is full view (select==choice schedule)? is right?

**Comment by RuffaloLavoisier** [comment]
![1656467700699](https://user-images.githubusercontent.com/66334969/177206519-fbe9377d-b76b-4f4e-8f87-f2563c9b4de6.png)

First design 👍

**Comment by RuffaloLavoisier** [comment]
Typically supported is the color, name, and time of the plan that you set in your calendar. This is limited to the Android I use, but I would appreciate it if you could check what information is displayed another mobile devices.

**Comment by RuffaloLavoisier** [comment]
Also, if you want to check your week's schedule, it's common, efficient, and in practice to check it on mobile. You can check only TODAY schedule on the watch. What is currently implemented is a simple framework and a sample.
