### ISSUE TITLE
Can't connect to WiFi

### ISSUE THREAD

**Issue by idpromnut** [Open-Smartwatch/open-smartwatch-os#158]
Hi, I have the v3.2 hardware and with both the latest HEAD and develop branches, I get the following errors when trying to connect to Wifi:
```
src/services/OswServiceTaskWiFi.cpp: [Mode] Off
========= Memory Monitor =========
core 0 (high):  824B of 4096B
core 1 (high):  1844B of 8192B
heap (high):    222388B of 307548B
heap (curr):    160468B of 307548B
========= Memory Monitor =========
core 0 (high):  824B of 4096B
core 1 (high):  1892B of 8192B
heap (high):    222388B of 307548B
heap (curr):    160468B of 307548B
include/osw_config.h: Accessing key id e
[E][Preferences.cpp:472] getString(): nvs_get_str len fail: e NOT_FOUND
========= Memory Monitor =========
core 0 (high):  824B of 4096B
core 1 (high):  1892B of 8192B
heap (high):    222396B of 307548B
heap (curr):    160468B of 307548B
src/services/OswServiceTaskWiFi.cpp: [Mode] Off
include/osw_config.h: Accessing key id i
[E][Preferences.cpp:472] getString(): nvs_get_str len fail: i NOT_FOUND
include/osw_config.h: Accessing key id a
[E][Preferences.cpp:472] getString(): nvs_get_str len fail: a NOT_FOUND
include/osw_config.h: Accessing key id b
[E][Preferences.cpp:472] getString(): nvs_get_str len fail: b NOT_FOUND
```

It looks like the MCU is resetting after that error and the monitor console is disocnnected.  I have also tried erasing the MCU's flash via the Erase build target. Configured in config.h:

CONFIG_WIFI_SSID
CONFIG_WIFI_PASS
DEVICE_NAME

**Comment by simonmicro** [comment]
Hey, those are not errors, just notes that those variables could not be found inside the local flash (and therefore the os defaults are used). The crashes on hardware revision 3.2 are known - and also noted there https://open-smartwatch.github.io/resources/hardware/ . Sadly there is nothing we can do about it right now...
