### ISSUE TITLE
Battery life

### ISSUE THREAD

**Issue by HerrAugust** [Open-Smartwatch/open-smartwatch-os#177]
Hello,

Does anyone know how long the smartwatch last with these settings?

- BLE kept enabled all the time and connected to my Android smartphone 
- Wifi kept disabled all the time
- screen kept normally all the time and only activated on notifications from the smartphone

An estimation based on your experience is fine!
Thank you a lot!

**Comment by uvwxy** [comment]
See https://github.com/Open-Smartwatch/open-smartwatch.github.io/issues/15
