### ISSUE TITLE
Battery indicator disappear

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#182]
# What is not working?

# How to reproduce this

Follow :
insert `-D RAW_SCREEN_SERVER` in `platformio.ini` build_flag - Light Edition V3.2
build + upload 
```
Since the clock turns off after 10 seconds, 
wait for the phenomenon by inputting a button so that it does not turn off.  
Or, it disappears when you run WiFi connection. 
But it(charger indicator) does not disappear after 10 seconds when you connect the charger.
```
# What should happen instead?

It can't disappear.

# Environment
- **Model** [e.g. Light Edition]
- **OSW-OS** [e.g. Git commit Hash] 
- **Browser** [e.g. Firefox, Chrome]
Model : `Light Edition V3.3`
branch : `develop`
Browser : `Chrome`

# Additional context
<img src="https://user-images.githubusercontent.com/66334969/145495915-c32b7c81-5242-4a54-bba1-410966b4affc.jpg" width="50%"><img src="https://user-images.githubusercontent.com/66334969/145495917-a4c90e9e-aa72-4993-9971-d9623336bd09.jpg" width="50%">

Is something colliding with each other?

**Comment by simonmicro** [comment]
https://github.com/Open-Smartwatch/open-smartwatch-os/blob/23232eb4ab1dd44ad7aa45463de78a7c177c2958/src/overlays/overlays.cpp#L50

This is because we can not utilitze

**Comment by simonmicro** [comment]
Just comment the check and watch what starts to happen. Spoiler: The ADC does not report _any_ realistic values anymore.

**Comment by RuffaloLavoisier** [comment]
@simonmicro Yes, that's right. It looked like a bug, so I thought it was a problem with the code..but It's a hardware problem.

**Comment by simonmicro** [comment]
I've specifically implemented a small delay until we disable the battery indicator, so you have at least a chance of reading it before we connect to WiFi :)
