### ISSUE TITLE
Autosleep timer doesnt reset when button is pressed

### ISSUE THREAD

**Issue by Chris3000-byte** [Open-Smartwatch/open-smartwatch-os#186]
Hi,

I have some uncertainty about how the watch goes to autosleep. My expectation would be, that whenever I press any button, the time that remains to go to sleep resets to the Display timeout time. 
But I found, that it only resets for the first app, that is registrated in the corresponding app switcher and also only when you press a button exactly at the time it would go to autosleep.

I found this in the code of the OswAppSwitcher class:

``` 
if (_enableAutoSleep && *_rtcAppIndex == 0 && !hal->btnIsDown(_btn)){
    short timeout = OswConfigAllKeys::settingDisplayTimeout.get();
    if (*_rtcAppIndex == 0 && (millis() - appOnScreenSince) > timeout * 1000) {
      if (hal->btnIsDown(BUTTON_1) || hal->btnIsDown(BUTTON_2) || hal->btnIsDown(BUTTON_3)) {
        appOnScreenSince = millis();
      } else if(timeout > 0) {
        Serial.print("Going to sleep after ");
        Serial.print(timeout);
        Serial.println(" seconds");
        this->sleep();
      }
    }
  }
```
Shouldnt the inner if-statement, that sets "appOnScreenSince" be outside the other if-statements?
Or do I misunderstand something?

**Comment by RuffaloLavoisier** [comment]
See #222
