### ISSUE TITLE
Initialize the framebuffer ?

### ISSUE THREAD

**Issue by max9901** [Open-Smartwatch/open-smartwatch-os#19]
Shalle we change malloc to calloc ?

or initialize the buffer to 0 imediatly when creating the buffer.

**Comment by uvwxy** [comment]
I will try this out.

**Comment by max9901** [comment]
it is fixed when u change:

`Graphics2D::enableBuffer()`

 `buffer[i] = (uint16_t*)malloc(width * chunkHeight * sizeof(uint16_t));`
 into 
` buffer[i] = new uint16_t[width * chunkHeight]();`
 
```
 new int[x]   -> not initialized 
 new int[x]() -> initialized to 0
 
```

**Comment by uvwxy** [comment]
Does this have any performance drawbacks?
Is it really required, especially as all/most apps do a `hal->gfx()->fill(...)` at the beginning?

**Comment by max9901** [comment]
No but i was hoping to get an initial face startup to go a little faster. By allowing for a basic first render at the setup of a face. 
So for example a digital watchface only loads the time at setup. and all other features will get added in the loop().
but tbh didn't really note a difference when experimenting yesterday with it.

'new[]()' is ofcourse a bit slower but it is faster then the 'gfx()->fill()' call and this way we are sure we never read un-initialed memory. Which adds value in my opinion.

**Comment by uvwxy** [comment]
Ok, I will change it accordingly
