### ISSUE TITLE
OSW-OS Emulator

### ISSUE THREAD

**Issue by simonmicro** [Open-Smartwatch/open-smartwatch-os#190]
Well... See the work on branch `feature/emulator`. Add your ideas / wishes down in the comments!

_I'm working on this in my free-time, so do not expect any results soon :tm:_

![visualization](https://media.giphy.com/media/SQgbkziuGrNxS/giphy.gif)

**Comment by RuffaloLavoisier** [comment]
Amazing....... :smile:

**Comment by simonmicro** [comment]
![image](https://user-images.githubusercontent.com/24966116/160822343-dfb46971-207c-4038-a6d2-11adaa75c546.png)

First progress :grin:

**Comment by RuffaloLavoisier** [comment]
OMG.................................. 
I think programming is a creative technology that God has allowed.

**Comment by RuffaloLavoisier** [comment]
I think it would be good to have debug messages about ui emulator

**Comment by simonmicro** [comment]
Yes, Serial emulation (for text) is also available. :)

**Comment by mat942** [comment]
This is great!! it could speed up dev so much for people without the physical device. Is there any chance we could add this to the docs on how to use it once its more stable (or is it already?)?

**Comment by simonmicro** [comment]
Sure thing! But currently I have (sadly) not enough time to continue it... , the f*ing `String`-class is not working properly, as it also has to be compatible to the `std::string` implementation and Arduino completely broke it... Brrr...

**Comment by simonmicro** [comment]
Heyho - I was so free and made some progress. I guess I'll be switching to SDL2 only (which makes the setup for devs easier as this is the only library needed) with ImGui. Here is a short demo :grin: :

https://user-images.githubusercontent.com/24966116/173259443-35e9a0a5-d7de-4e18-89ab-ab7cf86d7e3d.mp4

**Comment by RuffaloLavoisier** [comment]
@simonmicro 
LGTM

**Comment by simonmicro** [comment]
Latest update on our work... soon :tm:

![Screenshot from 2022-09-09 00-22-14](https://user-images.githubusercontent.com/24966116/189236360-71df4ed8-bf34-4014-a3a7-93ee2f3c9e05.png)
