### ISSUE TITLE
Arrange the order of the main screen elements

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#194]
# What is not working?

<img src="https://user-images.githubusercontent.com/66334969/157180770-16fde575-b0ac-463f-bd08-7b6c8d17615a.jpg" width="65%">

* Just , we need to arrange the order.(image sort)

# How to reproduce this

1. Until the number of steps in blue fills up half a lap. 
2. When the minute hand is between 25 and 35 minutes.

# What should happen instead?

* I think it would be better to see the images without each other covered. Wouldn't it be better to give priority at least?

# Environment
- **Model** [e.g. Light Edition]
- Light Edition 3.3
- **OSW-OS** [e.g. Git commit Hash]
- last version
- **Browser** [e.g. Firefox, Chrome]

# Additional context

**Comment by RuffaloLavoisier** [comment]
If it is approved, I will start implementing it.

**Comment by simonmicro** [comment]
Approved.
