### ISSUE TITLE
Step Counter cache problem and moving step of total

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#200]
<img src="https://user-images.githubusercontent.com/66334969/159154728-7283a6ce-849e-4a58-a7f6-b0610b94858f.gif" width="65%" >

# What is not working?

Currently, the step counter is working normally, but there is a slight problem saving the steps after the day. I'm worried about this problem.
 
As far as I know, when i infer the height of the blue square that appeared suddenly, it is confirmed that the current total steps is stored in `lastDoW`.

The `total-steps` is stored in the `lastDoW`.

we have to fix it or **wontfix**?

*I think it's a very minor problem, and I think it's a small exception and it's a part of it that doesn't cause much trouble with the operation.*

# How to reproduce this

1. Running and working , and check step counter

2. Please turn off the timeout and observe the step counter movement in midnight.

# What should happen instead?

# Environment
- **Model** [e.g. Light Edition]
`Light Edition 3.3`
- **OSW-OS** [e.g. Git commit Hash]
-`last commit`
- **Browser** [e.g. Firefox, Chrome]

# Additional context

**Comment by simonmicro** [comment]
Yes, this is known... Thanks for the report - will be fixed soon :tm:

**Comment by RuffaloLavoisier** [comment]
This is a previous issue related to this function.
https://github.com/Open-Smartwatch/open-smartwatch-os/issues/176
