### ISSUE TITLE
Flash memory stable

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#202]
```
RAM:   [==        ]  17.7% (used 57860 bytes from 327680 bytes)
Flash: [========  ]  80.2% (used 2102164 bytes from 2621440 bytes)
Building .pio/build/LIGHT_EDITION_V3_3/firmware.bin
esptool.py v3.1
Merged 1 ELF section
======================= [SUCCESS] Took 39.42 seconds ====================

Environment         Status    Duration
------------------  --------  ------------
LIGHT_EDITION_V3_3  SUCCESS   00:00:39.420
======================= 1 succeeded in 00:00:39.420 =======================
```
I solved the instability that has been raised by linking Bluetooth and Wi-Fi. 
Secure stable flash memory space.

**Comment by RuffaloLavoisier** [comment]
Ping @uvwxy @simonmicro

**Comment by simonmicro** [comment]
1. No need to ping, at least I get the notifications anyways.
2. What are you talking about? What did you solve? How did you solve it? What were the symptoms in the first place?

**Comment by RuffaloLavoisier** [comment]
> 2\. Or do you mean that compiling both WiFi && BLE was too big for the chip?

@simonmicro 

That's right

Our chip capacity was relatively small to use Bluetooth and Wi-Fi at the same time. 

So, as far as I know, we only use one , Bluetooth or Wi-Fi. 

However, by modifying the build partitions, we have secured enough space to compile. Please make sure that what I did is worthwhile.

**Comment by simonmicro** [comment]
As this would kill off our OTA capabilities, I'm closing this for now...

**Comment by RuffaloLavoisier** [comment]
Thanks
