### ISSUE TITLE
Rolling proximity identifiers

### ISSUE THREAD

**Issue by occ2018** [Open-Smartwatch/open-smartwatch-os#22]
With both bluetooth and wifi can you please somehow build https://en.wikipedia.org/wiki/Exposure_Notification inside these watches. Then one can have a nice dongle that can be used for many corona warning apps. 

your work is great - open - and inspiring. Thanks

**Comment by uvwxy** [comment]
@occ2018 Thank you for the suggestion. As we still have a lot to do, I will close this issue until we have the time for this :)
