### ISSUE TITLE
Add Fallback Wi-Fi

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#234]
I would like to add a Fallback-SSID (`cafe`, `school`...) so that Wi-Fi is connected even if it's not my main place(`home`). (*Security is yours!*)

*  It maybe doesn't need, but using AutoAP every time seems cumbersome.

**Comment by simonmicro** [comment]
This is also something I was thinking about! Go on, I think it is a good idea!

**Comment by uvwxy** [comment]
I think so, too.

Maybe call it "Fallback SSID"?  Secondary would imply a possible third and so on. I'd be too lazy to implement more than a second tuple of ssid/pass 😉

**Comment by RuffaloLavoisier** [comment]
I plan to save 2 more SSID. So a total of three

> Maybe call it "Fallback SSID"?

Ok, thanks 👍
