### ISSUE TITLE
NTP update error

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#254]
# What is not working?

Appears when trying to update NTP. maybe 3 time in 10 time.

# How to reproduce this
1. Go to 'Wi-Fi connect'
2. Click on 'connect and update'

If nothing happens, repeat this process.

# What should happen instead?

Just update local time.

# Environment
- **Model** [e.g. Light Edition]
LE_3.3
- **OSW-OS** [e.g. Git commit Hash]
70e1b4102c5e8d8bfbd002435421ce15868b1a0c
- **Browser** [e.g. Firefox, Chrome]

# Additional context

![KakaoTalk_20220705_222048507](https://user-images.githubusercontent.com/66334969/177337818-2bef0709-eb07-43c5-84b6-d8361bcf6b23.gif)

As NTP is updated, the update time changes to dual timezone, so internally shared functions seem to collide.

**Comment by simonmicro** [comment]
Maybe a bug - PLEASE add serial logs, because I've got a feeling in my gut, that this is caused by something logged there...

**Comment by RuffaloLavoisier** [comment]
```
src/services/OswServiceTaskWiFi.cpp: [NTP] Started update...
src/services/OswServiceTaskWiFi.cpp: [NTP] Update finished (time of 1657578106)!
src/services/OswServiceTaskWiFi.cpp: [NTP] Started update...
src/services/OswServiceTaskWiFi.cpp: [NTP] Update finished (time of 1657578107)!
src/services/OswServiceTaskWiFi.cpp: [NTP] Started update...
src/services/OswServiceTaskWiFi.cpp: [NTP] Update finished (time of 1657578107)!
src/services/OswServiceTaskWiFi.cpp: [NTP] Started update...
src/services/OswServiceTaskWiFi.cpp: [NTP] Update finished (time of 1657578108)!
src/services/OswServiceTaskWiFi.cpp: [NTP] Started update...
src/services/OswServiceTaskWiFi.cpp: [NTP] Update finished (time of 1657578109)!
src/services/OswServiceTaskWiFi.cpp: [NTP] Started update...
src/services/OswServiceTaskWiFi.cpp: [NTP] Update finished (time of 1657578110)!
src/services/OswServiceTaskWiFi.cpp: [NTP] Started update...
src/services/OswServiceTaskWiFi.cpp: [NTP] Update finished (time of 1657578120)!
```

The default log does not detect any anomalies...

**Comment by simonmicro** [comment]
So the issue occurred at?
> src/services/OswServiceTaskWiFi.cpp: [NTP] Update finished (time of 1657578110)!      //   Action !

There should be no such problem... Maybe the function inside `esp32.cpp` https://github.com/Open-Smartwatch/open-smartwatch-os/blob/2d9384ed69ba354fe81a7487a306ae90ad75ebe1/src/devices/esp32.cpp#L54 is broken because it does not properly initialize the struct to zero before using it?

**Comment by RuffaloLavoisier** [comment]
<img src="https://user-images.githubusercontent.com/66334969/178478103-4989c0af-9a1d-4491-87fd-c9c737de35cf.jpg" width="45%">
This is ERROR NTP update
<img src="https://user-images.githubusercontent.com/66334969/178478111-02384d78-ff3c-44df-9a70-c96958e5f835.jpg" width="45%">
This is My local-time
