### ISSUE TITLE
Auto-Build osw_wrap.cxx

### ISSUE THREAD

**Issue by uvwxy** [Open-Smartwatch/open-smartwatch-os#29]
See: https://github.com/Open-Smartwatch/open-smartwatch-os/pull/26

> Following can be used to regenerate the osw_wrap.cxx This should maybe be automated as part of the build process?
swig -c++ -lua -I../../include -I../../lib/Arduino_GFX osw.i

**Comment by uvwxy** [comment]
@Apfelwurm this might be something for you, if you have the time

Thanks in advance :)

**Comment by Apfelwurm** [comment]
Is now on my todo list :)
This should be easily possible via a prebuild/postbuild script within pio.

**Comment by Apfelwurm** [comment]
I think this one could be closed :)
