### ISSUE TITLE
Calculator app

### ISSUE THREAD

**Issue by ich2a** [Open-Smartwatch/open-smartwatch-os#293]
I created a calculator app. You can try it at https://github.com/ich2a/open-smartwatch-os/tree/develop. 
If anybody is interested, I would love to contribute with that app. 

![OswAppCalculator](https://user-images.githubusercontent.com/80181603/191523403-0e654765-8b65-4f58-ae35-cd6cd6475614.jpg)

**Comment by RuffaloLavoisier** [comment]
Hi there, LGTM.
If you want to contribute, open the PR to merge :)
