### ISSUE TITLE
About the Bluetooth feature

### ISSUE THREAD

**Issue by codermery** [Open-Smartwatch/open-smartwatch-os#323]
Hi,
I have a "LIGHT EDITION" smartwatch. However, I want to activate the Bluetooth feature over the "ESP32 Pico D4" and scan. But I am getting some errors. If you have an open source bluetooth code available, I'd like to try it.
I will be happy if you can help me.
Kind regards...

**Comment by simonmicro** [comment]
1. BLE is alpha at best. We are working on it in the background, but there if nothing official yet. (Psst, try an other BLE lib - the current code is too fat to use).
2. What errors? Care to share some logs?
3. ... #141 ?
