### ISSUE TITLE
Possibility to develop without the board? 

### ISSUE THREAD

**Issue by ffenix113** [Open-Smartwatch/open-smartwatch-os#35]
Hello, 

This seems like an awesome and interesting project, and I personally would be interested to play around and maybe even contribute.

But it would be nice to know if development and testing(at least somethung) can be achieved without having a board? For example with Qemu or similar.

**Comment by euanlc** [comment]
Hi, if you look at paul's instagram he has a post where he appears to be using an emulator. If you want information about that from him your best bet is to join the [discord](https://discord.gg/9QQuv6ta) to talk to him directly.
hope this helps,
euan

**Comment by cawolfkreo** [comment]
There is an amulator of sorts you can use as @euanlc mentioned, you can find it here: https://github.com/Open-Smartwatch/lib-open-smartwatch

**Comment by zbot473** [comment]
Someone would have to write an entire emulator with bindings to methods that fake or use the host's Wi-Fi/Bluetooth/Accelerometers/GPS/SD/Buttons

**Comment by ffenix113** [comment]
Thank you for the info. 

I will check out the graphics repo.
