### ISSUE TITLE
Fix typo on Docs/Project

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#365]
There are many typos in the project. This needs to be corrected.

**Comment by simonmicro** [comment]
You mentioned the use of `codespell` to search for those... Maybe we should also add hat to the CI?

**Comment by simonmicro** [comment]
I've unassigned myself, as I currently don't have the capacity to also work on this. If this remains a TODO for a while, I'll my add it to a milestone and take it over.

**Comment by RuffaloLavoisier** [comment]
> You mentioned the use of `codespell` to search for those... Maybe we should also add hat to the CI?

A double check is required to validate the results through CI. It's a wonderful tool, but it's just a tool. It is up to humans to double-check the results of the modification.
