### ISSUE TITLE
Check getBatteryPercent with drawUsbConnected

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#374]
![image](https://github.com/Open-Smartwatch/open-smartwatch-os/assets/66334969/0f7dffaf-afe7-4226-91ba-95d84fe370b7)

It would be nice if you could check how much the battery is charged even when it is currently being charged.

**Comment by uvwxy** [comment]
Is this for general OS support, or for the light v3.x?

I've been working with the MAX17043 with my latest builds, which intends to be used while the battery is not in use. This would make the approach similar to go by the voltage that is applied to the lipo by the charging circuit.

Probably the easiest would be to take the latest state of charge in % and then the time it has been charged?

**Comment by simonmicro** [comment]
With the current hardware releases, this is not possible, as we can only measure the voltage - during charging this is a fixed one... `MAX17043` is a battery-management-chip, which we would have to include in the future - then we can ask it using I2C what the levels are. I would close the issue for now, as we cannot implement it for now...

**Comment by RuffaloLavoisier** [comment]
I understand that the battery capacity can be measured while charging. I just want to express this on the display while charging.
