### ISSUE TITLE
[Question] Does Open-Smartwatch support cam, like ESP32 Cam OV5640, or any cam ? Thank you.

### ISSUE THREAD

**Issue by selfhostrepo** [Open-Smartwatch/open-smartwatch-os#377]
# What is not working?

# How to reproduce this

# What should happen instead?

# Environment
- **Model** [e.g. Light Edition]
- **OSW-OS** [e.g. Git commit Hash]
- **Browser** [e.g. Firefox, Chrome]

# Additional context

**Comment by simonmicro** [comment]
Theoretically yes? After all it is an ESP32 with only a limited amount of pins available. If you hack it together, the software is not restricted.
