### ISSUE TITLE
About the color of the flashlight

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#386]
https://github.com/Open-Smartwatch/open-smartwatch-os/blob/0607210a1ff0dacd2652a97b9af48df3e539da79/src/apps/tools/OswAppFlashLight.cpp#L36

Always, I think FlashLight recommended Color: `White`.

becauze FlashLight Color change from configuration setting.

**Comment by RuffaloLavoisier** [comment]
@Open-Smartwatch/osw-support 
How about you?

**Comment by simonmicro** [comment]
Yes. Absolutely! This should be fixed to white!
