### ISSUE TITLE
Watchfaces count bug

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#404]
# What is not working?
wrong calculate for watchfaces index.

# How to reproduce this

just click reset pwr button on emulator.

# What should happen instead?

# Environment
- **Model** [e.g. Light Edition]
- **OSW-OS** [e.g. Git commit Hash]
- **Browser** [e.g. Firefox, Chrome]

# Additional context

![image](https://github.com/user-attachments/assets/0778df84-2cfb-4ce0-b45a-8c152848b6cd)

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive password: changeme
I put the necessary dlls in the archive

**Comment by simonmicro** [comment]
I assume some global variable is not being tracked in the emulator, leading to filling this...

**Comment by simonmicro** [comment]
This was already fixed in #407
