### ISSUE TITLE
Workflow auto-release is not working

### ISSUE THREAD

**Issue by simonmicro** [Open-Smartwatch/open-smartwatch-os#416]
# What is not working?
As we merged v0.17.0 into the master branch, no draft-release was created. The `create-release` job was skipped. Manually creating the release, so the tag gets created also did not work, as the `check_skip` skipped the whole pipeline then...

# How to reproduce this
See ↑

# What should happen instead?
A new draft release, with text and artifacts should be created.

**Comment by RuffaloLavoisier** [comment]
My repo is working.. but it is from tag push...maybe skip from duplicate check workflow.
