### ISSUE TITLE
Rework watchface UI

### ISSUE THREAD

**Issue by Simonmicro** [Open-Smartwatch/open-smartwatch-os#53]
Here just some ideas - I would be happy to implement them!
* Analog/digital faces
  * Digital with different designs (maybe even showing dates?!)
* Configurable colors
* More prominent status-icons support (like wifi connected? ble? -> later on maybe media (on the possibly connected device) playing?)
* Primarily configured on compile-time, anything else will need something like a storage HAL and respective data structures

-> Do you guys have some inputs to this?

**Comment by uvwxy** [comment]
We have more than analog watch faces. I think we can add more faces as they appear in the wild ;)

I'm working on configurable colors now.
