### ISSUE TITLE
Make LUA support optional

### ISSUE THREAD

**Issue by Simonmicro** [Open-Smartwatch/open-smartwatch-os#56]
We have currently very limited resources running on the watch and there are currently no (?) apps using lua for this os. So I would like to see a way to `#define` it out via the config. Later on we could re-add it, but for now this should help us focus on the core problems: Random crashes & and a stable os.
This would also remove the need to install swig always when compiling the os, as only users with the _need_ for lua would use it.

I'm creating this issue, as I have currently no idea how swig integrates and where I would need to start (also no time :P).

**Comment by uvwxy** [comment]
working on this. will add a new env:pico32_LIGHT_EDITION_PREBUILD_LUA if you want to rebuild the cpp via swig.
