### ISSUE TITLE
No autosleep while buttons pressed

### ISSUE THREAD

**Issue by xasz** [Open-Smartwatch/open-smartwatch-os#71]
I often get confused by the watch going do deep sleep if i want to switch a face.
I am not sure if i just press too long and it is already handled or i just get the perfect timing of deep sleep auto timer is triggered while i hold down the button, when i want to switch a face :)

**Comment by uvwxy** [comment]
Does my latest change regarding the overlay drawing a frame until the app switch long press is detected help?
