### ISSUE TITLE
Change the drawThickLine function

### ISSUE THREAD

**Issue by max9901** [Open-Smartwatch/open-smartwatch-os#89]
Can we change the following in this function:

`void drawThickLine(int32_t x1, int32_t y1, int32_t x2, int32_t y2, uint8_t radius, uint16_t color)`

all entries of:
`drawCircle(x, y, radius - 1, color);`
to
`fillCircle(x, y, radius - 1, color);`

**Comment by uvwxy** [comment]
fixed with commit 900f9b6
