### ISSUE TITLE
CI/CD: build to verify pull requests compile

### ISSUE THREAD

**Issue by uvwxy** [Open-Smartwatch/open-smartwatch-os#9]
Verifying pull requests would be easier to see if the code still compiles.

**Comment by Apfelwurm** [comment]
I take care of this one :)

**Comment by uvwxy** [comment]
I will test this as soon as I'm done with #6

**Comment by Apfelwurm** [comment]
Seems to work (or dont work when it shouldnt) :)
https://github.com/Open-Smartwatch/open-smartwatch-os/pull/21

**Comment by uvwxy** [comment]
Yes it does :). Thank you!
