### ISSUE TITLE
Watchface changes to default analog when tapped after wakeup

### ISSUE THREAD

**Issue by plungepool** [Open-Smartwatch/open-smartwatch-os#95]
Hi, not sure if this is a known issue, but I've noticed that if I select the digital or binary watchface, the OSW will remember what it was set to, unless the watch is tapped or jostled more than is required to wake it up in which case it resets back to the analog watchface. Was experimenting trying to figure out if perhaps it switching back had anything to do with the step counter being triggered but could not confirm. Willing to try and investigate further when I get a chance.

**Comment by uvwxy** [comment]
What git revision is affected by this?

**Comment by uvwxy** [comment]
please check with the latest master again. thank you!

**Comment by plungepool** [comment]
That does it! Thanks!!
