### ISSUE TITLE
extra light release

### ISSUE THREAD

**Issue by mat942** [Open-Smartwatch/open-smartwatch-os#98]
Would like to propose an extra light release without connectivity for just the time watchface and manual time setting.

**Comment by matti04** [comment]
Hi, kindly elaborate why you think so. What do you think is the advantage of an extra light release?
The hardware for the light edition is already quite affordable, and low-power. 
Regards, Matteo

**Comment by mat942** [comment]
Hi, I'm thinking same hardware but having the possibility to flash an extra light release for a greater battery life and endurance in environment without connectivity.

**Comment by uvwxy** [comment]
@mat942  I understand what you mean.

Would you be happy with a separate branch for this?

**Comment by mat942** [comment]
Sure!

**Comment by mat942** [comment]
any progress anyone?

**Comment by mat942** [comment]
anyone on this?

**Comment by Simonmicro** [comment]
Nope - but you could use the latest dev release and just turn off all features inside the web ui... This leaves you with a nearly minimal build... You may have to live with the step counter, which can't be turned of (yet?).

**Comment by uvwxy** [comment]
Idea:

Split the time setting app into a "manual only" and "update from internet". If I remember correctly @Simonmicro rewrote the wifi service to reresh the time automatically in any case, so we could skip the latter.

**Comment by Simonmicro** [comment]
>  reresh the time automatically in any case, so we could skip the latter

Only if the user enabled this. Alternatively the user should still have the ability to manually trigger a refresh.

> Split the time setting app into a "manual only" and "update from internet".

How about the top button to set it manually and the bottom to connect and then to fetch it that way? Are we not already doing this?

**Comment by uvwxy** [comment]
@mat942 Please see the latest develop branch.

Add the following line to your config.h:

```
#define SERVICE_WIFI 0
```

Then you can flash a firmware version without wifi, and the config app only allows manual setting of time.

**Comment by simonmicro** [comment]
Hey, with #142 you'll get more granular control over what you want to compile in. Checkout the latest `develop` to get started!

Enjoy.

**Comment by mat942** [comment]
Hi! @simonmicro I think it would be great to list the flags somewhere of what can be enabled and disabled. the #define SERVICE_WIFI 0 that paul mentions above is only know to those who take a look at this issue. maybe a page in the docs or something else could be a nice to have!

**Comment by simonmicro** [comment]
Hmm, good point. Currently multiple flags are supported, some of which are listed in the `platformio.ini`... Could you create an issue inside the documentation repo for this? Maybe @RuffaloLavoisier could help me with collecting them (next meeting :wink: ?)?

**Comment by RuffaloLavoisier** [comment]
Like it -  I marked add it to the next topic.
